/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x4b3ad8 = _0x3ab7;
function _0x3ab7(_0xbe1b31, _0x58316f) {
    const _0x36632e = _0x3663();
    return _0x3ab7 = function (_0x3ab780, _0x3216f5) {
        _0x3ab780 = _0x3ab780 - 0x164;
        let _0x52fb24 = _0x36632e[_0x3ab780];
        return _0x52fb24;
    }, _0x3ab7(_0xbe1b31, _0x58316f);
}
function _0x3663() {
    const _0x2f6984 = [
        'error',
        'write',
        'service',
        'PUT',
        'data',
        '6255nvsYjq',
        'chtBq',
        'method',
        'serialize',
        'Message\x20must\x20be\x20an\x20array',
        'application/json',
        '4199120VMzeNg',
        'end',
        '18NyuzxK',
        '7WdVspn',
        'node',
        'ArQtE',
        'riaoV',
        'Error\x20on\x20response',
        'length',
        '801668JlBEde',
        '2773010yzcScd',
        '396yxByHk',
        'FCCyR',
        'fqbJY',
        'exports',
        '178iFopDs',
        '1475463MrNuPT',
        '4398414grMpGk',
        'bjhXU',
        '1719656HOsAvs',
        '10UbLNrY'
    ];
    _0x3663 = function () {
        return _0x2f6984;
    };
    return _0x3663();
}
(function (_0x40a489, _0x52fdf3) {
    const _0x42ef7b = _0x3ab7, _0x45c97d = _0x40a489();
    while (!![]) {
        try {
            const _0x31523f = -parseInt(_0x42ef7b(0x172)) / 0x1 + -parseInt(_0x42ef7b(0x178)) / 0x2 * (parseInt(_0x42ef7b(0x183)) / 0x3) + parseInt(_0x42ef7b(0x17c)) / 0x4 * (-parseInt(_0x42ef7b(0x17d)) / 0x5) + -parseInt(_0x42ef7b(0x17a)) / 0x6 + parseInt(_0x42ef7b(0x16c)) / 0x7 * (-parseInt(_0x42ef7b(0x169)) / 0x8) + -parseInt(_0x42ef7b(0x16b)) / 0x9 * (parseInt(_0x42ef7b(0x173)) / 0xa) + parseInt(_0x42ef7b(0x179)) / 0xb * (parseInt(_0x42ef7b(0x174)) / 0xc);
            if (_0x31523f === _0x52fdf3)
                break;
            else
                _0x45c97d['push'](_0x45c97d['shift']());
        } catch (_0x2eb011) {
            _0x45c97d['push'](_0x45c97d['shift']());
        }
    }
}(_0x3663, 0xbb32f));
const http = require('http'), serialization = require('../util/serialization'), comm = {};
comm['send'] = function (_0x2df79d, _0xa3cc8f, _0x2e5ebe) {
    const _0x558405 = _0x3ab7, _0x3a060c = {
            'AXwWK': function (_0x96beb5, ..._0x48f7af) {
                return _0x96beb5(..._0x48f7af);
            },
            'lYSyY': 'end',
            'FCCyR': _0x558405(0x17e),
            'kKGSo': function (_0xac67d3, _0x1fb2a3) {
                return _0xac67d3(_0x1fb2a3);
            },
            'ArQtE': function (_0x2ef57a, _0x4fe417) {
                return _0x2ef57a instanceof _0x4fe417;
            },
            'bjhXU': _0x558405(0x167),
            'vuUAG': function (_0x15a2c7, _0x827493) {
                return _0x15a2c7 + _0x827493;
            },
            'fqbJY': function (_0x2d60f0, _0x2b1901) {
                return _0x2d60f0 + _0x2b1901;
            },
            'riaoV': _0x558405(0x181),
            'OPhVj': _0x558405(0x168)
        };
    if (_0x3a060c[_0x558405(0x16e)](!_0x2df79d, Array))
        throw new Error(_0x3a060c[_0x558405(0x17b)]);
    let _0x2b9bd5 = _0xa3cc8f[_0x558405(0x16d)], _0x357d78 = _0xa3cc8f[_0x558405(0x180)], _0x521ad4 = _0xa3cc8f[_0x558405(0x165)], _0x2781ce = serialization[_0x558405(0x166)](_0x2df79d);
    const _0x16ab96 = {
            'hostname': _0x2b9bd5['ip'],
            'port': _0x2b9bd5['port'],
            'path': _0x3a060c['vuUAG'](_0x3a060c[_0x558405(0x176)]('/' + _0x357d78, '/'), _0x521ad4),
            'method': _0x3a060c[_0x558405(0x16f)],
            'headers': {
                'Content-Type': _0x3a060c['OPhVj'],
                'Content-Length': _0x2781ce[_0x558405(0x171)]
            }
        }, _0xc60829 = http['request'](_0x16ab96, _0x464773 => {
            const _0x2000b7 = _0x558405, _0x5300f3 = {
                    'chtBq': function (_0x285aeb, ..._0x22c400) {
                        return _0x3a060c['AXwWK'](_0x285aeb, ..._0x22c400);
                    }
                };
            let _0x275145 = '';
            _0x464773['on'](_0x2000b7(0x182), function (_0x4bf7b5) {
                _0x275145 += _0x4bf7b5;
            }), _0x464773['on'](_0x3a060c['lYSyY'], function () {
                _0x2e5ebe && _0x5300f3['chtBq'](_0x2e5ebe, ...serialization['deserialize'](_0x275145));
            }), _0x464773['on'](_0x3a060c[_0x2000b7(0x175)], function (_0x7c3a77) {
                const _0x1183b6 = _0x2000b7;
                _0x2e5ebe && _0x5300f3[_0x1183b6(0x164)](_0x2e5ebe, new Error(_0x1183b6(0x170)));
            });
        });
    _0xc60829['on'](_0x3a060c['FCCyR'], function (_0x5468d9) {
        _0x2e5ebe && _0x3a060c['kKGSo'](_0x2e5ebe, new Error(_0x5468d9));
    }), _0xc60829[_0x558405(0x17f)](_0x2781ce), _0xc60829[_0x558405(0x16a)]();
}, module[_0x4b3ad8(0x177)] = comm;/* eslint-enable */
