/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x1b0eba = _0x2285;
function _0x2285(_0x72afeb, _0x499eb5) {
    const _0x301f90 = _0x301f();
    return _0x2285 = function (_0x22851d, _0x5aad25) {
        _0x22851d = _0x22851d - 0xe7;
        let _0x2000be = _0x301f90[_0x22851d];
        return _0x2000be;
    }, _0x2285(_0x72afeb, _0x499eb5);
}
(function (_0x4aa34d, _0xdeee37) {
    const _0xb8366a = _0x2285, _0x2f862e = _0x4aa34d();
    while (!![]) {
        try {
            const _0x232fe5 = parseInt(_0xb8366a(0xf1)) / 0x1 + -parseInt(_0xb8366a(0x106)) / 0x2 * (parseInt(_0xb8366a(0xf6)) / 0x3) + parseInt(_0xb8366a(0x10d)) / 0x4 * (parseInt(_0xb8366a(0xed)) / 0x5) + parseInt(_0xb8366a(0x108)) / 0x6 + -parseInt(_0xb8366a(0xfd)) / 0x7 * (-parseInt(_0xb8366a(0x10b)) / 0x8) + parseInt(_0xb8366a(0xf2)) / 0x9 + parseInt(_0xb8366a(0x107)) / 0xa * (-parseInt(_0xb8366a(0xfb)) / 0xb);
            if (_0x232fe5 === _0xdeee37)
                break;
            else
                _0x2f862e['push'](_0x2f862e['shift']());
        } catch (_0x21a4e6) {
            _0x2f862e['push'](_0x2f862e['shift']());
        }
    }
}(_0x301f, 0x95efe));
let groupsStore = new Map();
groupsStore[_0x1b0eba(0xfe)] = {};
function _0x301f() {
    const _0xe112c8 = [
        'routes',
        '484655kegbMC',
        'UhKyq',
        'unpuZ',
        'exports',
        '1180773NQTmtS',
        '7491258UDbYwl',
        'comm',
        'gossip',
        'IYPXt',
        '123qZxiMp',
        'store',
        'OzVPl',
        '\x20not\x20found',
        'XatXw',
        '44VjOuus',
        'getSID',
        '777nByFBi',
        'all',
        'Phali',
        'distribution',
        'put',
        'FIMIi',
        'mem',
        'uktHq',
        'NlBAE',
        '57364MATCMn',
        '4745830XoVMsj',
        '7014678ugxPbk',
        'EMLyk',
        'keys',
        '29496eQIrSc',
        'gid',
        '4biZUEq',
        'VPlFB',
        'Group\x20',
        'status',
        'gCpnM',
        'string',
        'rem'
    ];
    _0x301f = function () {
        return _0xe112c8;
    };
    return _0x301f();
}
const id = require('../util/id'), groups = {};
groups['get'] = function (_0x3afcbc, _0x4a54e0) {
    const _0x9604b5 = _0x1b0eba, _0x3e939a = {
            'OzVPl': function (_0x18e471, _0x1a5ff9, _0x54de8a) {
                return _0x18e471(_0x1a5ff9, _0x54de8a);
            },
            'FIMIi': function (_0x4f45ff, _0x82ae39) {
                return _0x4f45ff(_0x82ae39);
            }
        };
    _0x4a54e0 = _0x4a54e0 || function () {
    }, _0x3afcbc in groupsStore ? _0x3e939a[_0x9604b5(0xf8)](_0x4a54e0, null, groupsStore[_0x3afcbc]) : _0x3e939a[_0x9604b5(0x102)](_0x4a54e0, new Error(_0x9604b5(0xe7) + _0x3afcbc + '\x20not\x20found'));
}, groups[_0x1b0eba(0x101)] = function (_0x59bb00, _0x1997fd, _0x29a242) {
    const _0xe0ee85 = _0x1b0eba, _0x4f35f0 = {
            'uktHq': _0xe0ee85(0xfe),
            'Phali': function (_0x150eb3, _0x2bd908) {
                return _0x150eb3 || _0x2bd908;
            },
            'unpuZ': function (_0x93cad9, _0x3f3f77) {
                return _0x93cad9 === _0x3f3f77;
            },
            'EMLyk': _0xe0ee85(0xea),
            'YQlkN': function (_0x25ce84, _0x4dd998, _0x25fecf) {
                return _0x25ce84(_0x4dd998, _0x25fecf);
            }
        };
    _0x1997fd = _0x4f35f0[_0xe0ee85(0xff)](_0x1997fd, {}), _0x4f35f0[_0xe0ee85(0xef)](typeof _0x59bb00, _0x4f35f0[_0xe0ee85(0x109)]) && (_0x59bb00 = { 'gid': _0x59bb00 }), groupsStore[_0x59bb00['gid']] = _0x1997fd, Object[_0xe0ee85(0x10a)](_0x1997fd)['forEach'](_0x417cb5 => {
        const _0x53d53e = _0xe0ee85;
        groupsStore[_0x4f35f0[_0x53d53e(0x104)]][id[_0x53d53e(0xfc)](_0x1997fd[_0x417cb5])] = _0x1997fd[_0x417cb5];
    }), global['distribution'][_0x59bb00[_0xe0ee85(0x10c)]] = {}, global[_0xe0ee85(0x100)][_0x59bb00[_0xe0ee85(0x10c)]][_0xe0ee85(0xe8)] = require('../all/status')(_0x59bb00), global['distribution'][_0x59bb00[_0xe0ee85(0x10c)]][_0xe0ee85(0xf3)] = require('../all/comm')(_0x59bb00), global['distribution'][_0x59bb00['gid']][_0xe0ee85(0xf4)] = require('../all/gossip')(_0x59bb00), global[_0xe0ee85(0x100)][_0x59bb00[_0xe0ee85(0x10c)]]['groups'] = require('../all/groups')(_0x59bb00), global['distribution'][_0x59bb00[_0xe0ee85(0x10c)]][_0xe0ee85(0xec)] = require('../all/routes')(_0x59bb00), global[_0xe0ee85(0x100)][_0x59bb00[_0xe0ee85(0x10c)]][_0xe0ee85(0x103)] = require('../all/mem')(_0x59bb00), global[_0xe0ee85(0x100)][_0x59bb00['gid']][_0xe0ee85(0xf7)] = require('../all/store')(_0x59bb00), global[_0xe0ee85(0x100)][_0x59bb00['gid']]['mr'] = require('../all/mr')(_0x59bb00), _0x4f35f0['YQlkN'](_0x29a242, null, _0x1997fd);
}, groups['del'] = function (_0x5c1a43, _0x31183c) {
    const _0x5ab58e = _0x1b0eba, _0x508e94 = {
            'NlBAE': function (_0x12f643, _0x38570b) {
                return _0x12f643 in _0x38570b;
            },
            'Jeytw': function (_0x2e0cf1, _0x14b2b8, _0x2588c2) {
                return _0x2e0cf1(_0x14b2b8, _0x2588c2);
            },
            'gCpnM': function (_0x27b82e, _0xdd3a22) {
                return _0x27b82e(_0xdd3a22);
            }
        };
    if (_0x508e94[_0x5ab58e(0x105)](_0x5c1a43, groupsStore)) {
        let _0x5bced9 = groupsStore[_0x5c1a43];
        delete groupsStore[_0x5c1a43], _0x508e94['Jeytw'](_0x31183c, null, _0x5bced9);
    } else
        _0x508e94[_0x5ab58e(0xe9)](_0x31183c, new Error(_0x5ab58e(0xe7) + _0x5c1a43 + _0x5ab58e(0xf9)));
}, groups['add'] = function (_0x2c3c89, _0x11aec4, _0x19af8c) {
    const _0x39c1ed = _0x1b0eba, _0x7ab561 = {
            'IYPXt': function (_0x3d5829, _0x332c64) {
                return _0x3d5829 in _0x332c64;
            },
            'VPlFB': _0x39c1ed(0xfe),
            'UhKyq': function (_0x2a35c1, _0x7314a7, _0x6eef27) {
                return _0x2a35c1(_0x7314a7, _0x6eef27);
            }
        };
    _0x19af8c = _0x19af8c || function () {
    }, _0x7ab561[_0x39c1ed(0xf5)](_0x2c3c89, groupsStore) ? (!groupsStore[_0x2c3c89] && (groupsStore[_0x2c3c89] = {}), groupsStore[_0x2c3c89][id[_0x39c1ed(0xfc)](_0x11aec4)] = _0x11aec4, groupsStore[_0x7ab561[_0x39c1ed(0x10e)]][id[_0x39c1ed(0xfc)](_0x11aec4)] = _0x11aec4, _0x19af8c && _0x7ab561[_0x39c1ed(0xee)](_0x19af8c, null, groupsStore[_0x2c3c89])) : _0x19af8c && _0x19af8c(new Error(_0x39c1ed(0xe7) + _0x2c3c89 + _0x39c1ed(0xf9)));
}, groups[_0x1b0eba(0xeb)] = function (_0x232f5d, _0x52fd31, _0x538d23) {
    const _0x5ca593 = _0x1b0eba, _0x2870ed = {
            'PJSUQ': _0x5ca593(0xfe),
            'XatXw': function (_0x3bed5b, _0x448708, _0x1a9878) {
                return _0x3bed5b(_0x448708, _0x1a9878);
            },
            'gxWTJ': function (_0x3561d9, _0x43b9df) {
                return _0x3561d9(_0x43b9df);
            }
        };
    _0x538d23 = _0x538d23 || function () {
    }, _0x232f5d in groupsStore ? (delete groupsStore[_0x232f5d][_0x52fd31], delete groupsStore[_0x2870ed['PJSUQ']][_0x52fd31], _0x2870ed[_0x5ca593(0xfa)](_0x538d23, null, groupsStore[_0x232f5d])) : _0x2870ed['gxWTJ'](_0x538d23, new Error('Group\x20' + _0x232f5d + '\x20not\x20found'));
}, module[_0x1b0eba(0xf0)] = groups;/* eslint-enable */
