/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x3780b1 = _0x357b;
function _0x402e() {
    const _0x1219c4 = [
        '68358kmzAqt',
        '--config',
        ';\x0a\x0a\x20\x20\x20\x20let\x20callbackRPC\x20=\x20',
        'inherit',
        'memoryUsage',
        'heapUsed',
        'Status\x20key\x20not\x20found',
        'get',
        '7imHXMm',
        ';\x0a\x0a\x20\x20\x20\x20try\x20{\x0a\x20\x20\x20\x20\x20\x20\x20\x20onStart();\x0a\x20\x20\x20\x20\x20\x20\x20\x20callbackRPC(null,\x20global.nodeConfig,\x20()\x20=>\x20{});\x0a\x20\x20\x20\x20}\x0a\x20\x20\x20\x20catch\x20(e)\x20{\x0a\x20\x20\x20\x20\x20\x20\x20\x20callbackRPC(e,\x20null,\x20()\x20=>\x20{});\x0a\x20\x20\x20\x20}\x0a\x20\x20\x20\x20',
        'crekv',
        'createRPC',
        '12981EGyaks',
        '247742CEQnfl',
        'iIvMc',
        '12303hodFph',
        'cqRhz',
        'join',
        '1060dwBpxF',
        '\x0a\x20\x20\x20\x20let\x20onStart\x20=\x20',
        'node',
        '20QAqkEM',
        'distribution',
        'tojGe',
        'bgtid',
        'yPASM',
        'getNID',
        '13145660AFIEtg',
        'getSID',
        '5wusisA',
        '2248756VHUKmT',
        'NqNhw',
        'exit',
        'onStart',
        'OpBCV',
        'heapTotal',
        'SAEgQ',
        'toString',
        '3629072mJVaJg',
        'nodeConfig',
        'util',
        'serialize',
        'moreStatus'
    ];
    _0x402e = function () {
        return _0x1219c4;
    };
    return _0x402e();
}
(function (_0x5564b3, _0x53e0f2) {
    const _0x58ac35 = _0x357b, _0x128dc4 = _0x5564b3();
    while (!![]) {
        try {
            const _0x182ddc = parseInt(_0x58ac35(0x10c)) / 0x1 + parseInt(_0x58ac35(0xe9)) / 0x2 * (parseInt(_0x58ac35(0x10b)) / 0x3) + parseInt(_0x58ac35(0xf2)) / 0x4 * (-parseInt(_0x58ac35(0xf1)) / 0x5) + -parseInt(_0x58ac35(0xff)) / 0x6 * (parseInt(_0x58ac35(0x107)) / 0x7) + -parseInt(_0x58ac35(0xfa)) / 0x8 + -parseInt(_0x58ac35(0x10e)) / 0x9 * (parseInt(_0x58ac35(0x111)) / 0xa) + parseInt(_0x58ac35(0xef)) / 0xb;
            if (_0x182ddc === _0x53e0f2)
                break;
            else
                _0x128dc4['push'](_0x128dc4['shift']());
        } catch (_0x12c246) {
            _0x128dc4['push'](_0x128dc4['shift']());
        }
    }
}(_0x402e, 0x4ca62));
const id = require('../util/id'), status = {};
global[_0x3780b1(0xfe)] = {
    'sid': id[_0x3780b1(0xf0)](global[_0x3780b1(0xfb)]),
    'nid': id[_0x3780b1(0xee)](global[_0x3780b1(0xfb)]),
    'counts': 0x0
}, status[_0x3780b1(0x106)] = function (_0x140be4, _0x583b76) {
    const _0x27369f = _0x3780b1, _0x39156c = {
            'qzCnp': function (_0x5346e0, _0x4fdbc7) {
                return _0x5346e0 in _0x4fdbc7;
            },
            'NqNhw': function (_0x2c49bb, _0x488448, _0x43c1ce) {
                return _0x2c49bb(_0x488448, _0x43c1ce);
            },
            'bgtid': function (_0x200fb4, _0x3e83ff) {
                return _0x200fb4 in _0x3e83ff;
            },
            'iIvMc': function (_0x40a220, _0x18effb, _0x2dad4d) {
                return _0x40a220(_0x18effb, _0x2dad4d);
            },
            'OpBCV': 'heapTotal',
            'SAEgQ': function (_0x4da2c6, _0x5731c0) {
                return _0x4da2c6 === _0x5731c0;
            },
            'cqRhz': 'heapUsed',
            'crekv': function (_0x21df63, _0x244dcd) {
                return _0x21df63(_0x244dcd);
            },
            'uPOFD': _0x27369f(0x105)
        };
    _0x583b76 = _0x583b76 || function () {
    };
    if (_0x39156c['qzCnp'](_0x140be4, global[_0x27369f(0xfb)]))
        _0x39156c[_0x27369f(0xf3)](_0x583b76, null, global['nodeConfig'][_0x140be4]);
    else {
        if (_0x39156c[_0x27369f(0xec)](_0x140be4, moreStatus))
            _0x39156c[_0x27369f(0x10d)](_0x583b76, null, moreStatus[_0x140be4]);
        else {
            if (_0x140be4 === _0x39156c[_0x27369f(0xf6)])
                _0x39156c[_0x27369f(0x10d)](_0x583b76, null, process[_0x27369f(0x103)]()[_0x27369f(0xf7)]);
            else
                _0x39156c[_0x27369f(0xf8)](_0x140be4, _0x39156c[_0x27369f(0x10f)]) ? _0x583b76(null, process[_0x27369f(0x103)]()[_0x27369f(0x104)]) : _0x39156c[_0x27369f(0x109)](_0x583b76, new Error(_0x39156c['uPOFD']));
        }
    }
};
const path = require('path'), {spawn} = require('child_process'), wire = require('../util/wire'), createActualCallback = function (_0x1ccb72, _0x33d3a7) {
        const _0x152602 = _0x3780b1;
        let _0x86e8dd = _0x152602(0x112) + _0x1ccb72['toString']() + _0x152602(0x101) + wire[_0x152602(0x10a)](wire['toAsync'](_0x33d3a7))[_0x152602(0xf9)]() + _0x152602(0x108);
        return new Function(_0x86e8dd);
    };
function _0x357b(_0x554e3e, _0x2677c5) {
    const _0x402ef8 = _0x402e();
    return _0x357b = function (_0x357ba6, _0x2b3fde) {
        _0x357ba6 = _0x357ba6 - 0xe8;
        let _0x4c63c9 = _0x402ef8[_0x357ba6];
        return _0x4c63c9;
    }, _0x357b(_0x554e3e, _0x2677c5);
}
status['spawn'] = function (_0x341270, _0x3662e4) {
    const _0x255aaf = _0x3780b1, _0x256de3 = {
            'uSIQp': '../../distribution.js',
            'tojGe': function (_0x2510db, _0x2885e5, _0x2a196c, _0xddeaf6) {
                return _0x2510db(_0x2885e5, _0x2a196c, _0xddeaf6);
            },
            'yPASM': _0x255aaf(0xe8),
            'IhUra': _0x255aaf(0x100)
        };
    let _0x1721dc = _0x341270;
    _0x1721dc[_0x255aaf(0xf5)] = _0x1721dc[_0x255aaf(0xf5)] || function () {
    }, _0x1721dc['onStart'] = createActualCallback(_0x1721dc['onStart'], _0x3662e4);
    const _0xfef6b = path[_0x255aaf(0x110)](__dirname, _0x256de3['uSIQp']);
    let _0x171d4c = _0x256de3[_0x255aaf(0xeb)](spawn, _0x256de3[_0x255aaf(0xed)], [
        _0xfef6b,
        _0x256de3['IhUra'],
        global[_0x255aaf(0xea)][_0x255aaf(0xfc)][_0x255aaf(0xfd)](_0x1721dc)
    ], {
        'detached': !![],
        'stdio': _0x255aaf(0x102)
    });
    _0x171d4c;
}, status['stop'] = function (_0x515397) {
    const _0x14d11e = _0x3780b1, _0x412aed = {
            'ITzqo': function (_0xd52a94, _0x33a358, _0x45cadb) {
                return _0xd52a94(_0x33a358, _0x45cadb);
            }
        };
    _0x515397 = _0x515397 || function () {
    }, _0x412aed['ITzqo'](_0x515397, null, global[_0x14d11e(0xfb)]), process[_0x14d11e(0xf4)](0x0);
}, module['exports'] = status;/* eslint-enable */
