/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
(function (_0x505f4e, _0x2b0c44) {
    const _0x3b66c7 = _0x1497, _0x465a2d = _0x505f4e();
    while (!![]) {
        try {
            const _0x495ab2 = -parseInt(_0x3b66c7(0x1ff)) / 0x1 + parseInt(_0x3b66c7(0x1f2)) / 0x2 + parseInt(_0x3b66c7(0x1ef)) / 0x3 + parseInt(_0x3b66c7(0x1f5)) / 0x4 * (-parseInt(_0x3b66c7(0x1fa)) / 0x5) + parseInt(_0x3b66c7(0x204)) / 0x6 * (parseInt(_0x3b66c7(0x1f3)) / 0x7) + -parseInt(_0x3b66c7(0x203)) / 0x8 + parseInt(_0x3b66c7(0x1f7)) / 0x9;
            if (_0x495ab2 === _0x2b0c44)
                break;
            else
                _0x465a2d['push'](_0x465a2d['shift']());
        } catch (_0x1f4767) {
            _0x465a2d['push'](_0x465a2d['shift']());
        }
    }
}(_0x1c2e, 0x6e601));
const fs = require('fs'), {idToNum, getID} = require('../distribution/util/id'), path = require('path');
function _0x1c2e() {
    const _0x14e7aa = [
        'existsSync',
        'NOTE:\x20This\x20is\x20an\x20auxiliary\x20file\x20created\x20by\x20oracle.js.\x0a',
        'length',
        '1110090MkVbYZ',
        'gkZgW',
        'FaQIg',
        '852566MfEPgd',
        '5089EVeKhK',
        'hash',
        '4xBnbUy',
        'NtFgw',
        '6560091gJiLgC',
        'It\x20can\x20be\x20safely\x20deleted.\x0a',
        'oOAgU',
        '3454095SIPyMV',
        'NXUuZ',
        'eWzfp',
        'qxjRN',
        'lMtiP',
        '724998fOMSWK',
        'sort',
        'map',
        'xWMEo',
        '2254328QbuSVB',
        '5154aLdpcX',
        'mmuyz'
    ];
    _0x1c2e = function () {
        return _0x14e7aa;
    };
    return _0x1c2e();
}
function naiveHashAux(_0x590298, _0x291066) {
    const _0x30f92b = _0x1497, _0x2a6691 = {
            'eWzfp': function (_0x2568e0, _0xf728be) {
                return _0x2568e0(_0xf728be);
            }
        };
    return _0x291066[_0x2a6691[_0x30f92b(0x1fc)](idToNum, _0x590298) % _0x291066[_0x30f92b(0x1ee)]];
}
function consistentHashAux(_0x5546a5, _0x25ddb4) {
    const _0x5cd0f0 = _0x1497, _0x2d9fe9 = {
            'lMtiP': function (_0x1c1809, _0x58e0c0) {
                return _0x1c1809(_0x58e0c0);
            },
            'vWoOq': function (_0x51d046, _0x12f3fa) {
                return _0x51d046 <= _0x12f3fa;
            }
        }, _0x1902e3 = _0x2d9fe9[_0x5cd0f0(0x1fe)](idToNum, _0x5546a5), _0x23541c = _0x25ddb4[_0x5cd0f0(0x201)](_0x54d59f => ({
            'id': _0x54d59f,
            'hash': idToNum(_0x54d59f)
        }));
    _0x23541c[_0x5cd0f0(0x200)]((_0x25df44, _0x514339) => _0x25df44[_0x5cd0f0(0x1f4)] - _0x514339[_0x5cd0f0(0x1f4)]);
    for (let _0xb0d3e of _0x23541c) {
        if (_0x2d9fe9['vWoOq'](_0x1902e3, _0xb0d3e[_0x5cd0f0(0x1f4)]))
            return _0xb0d3e['id'];
    }
    return _0x23541c[0x0]['id'];
}
function rendezvousHashAux(_0x203c6c, _0x187223) {
    const _0x232b2b = _0x1497, _0x46f8ee = {
            'xWMEo': function (_0x1f194d, _0x45be7c) {
                return _0x1f194d(_0x45be7c);
            },
            'FaQIg': function (_0x53b59b, _0x4b123e) {
                return _0x53b59b + _0x4b123e;
            },
            'tHzrq': function (_0x5d7073, _0x17afcb) {
                return _0x5d7073(_0x17afcb);
            },
            'oOAgU': function (_0x4866ba, _0x3b872e) {
                return _0x4866ba > _0x3b872e;
            }
        };
    let _0xbe172d = 0x0, _0x5ba237 = null;
    for (let _0x13ae1c of _0x187223) {
        let _0x34964b = _0x46f8ee[_0x232b2b(0x202)](getID, _0x46f8ee[_0x232b2b(0x1f1)](_0x203c6c, _0x13ae1c)), _0x4073e9 = _0x46f8ee['tHzrq'](idToNum, _0x34964b);
        _0x46f8ee[_0x232b2b(0x1f9)](_0x4073e9, _0xbe172d) && (_0xbe172d = _0x4073e9, _0x5ba237 = _0x13ae1c);
    }
    return _0x5ba237;
}
function _0x1497(_0x1fe7cf, _0x44ce33) {
    const _0x1c2eca = _0x1c2e();
    return _0x1497 = function (_0x1497dc, _0x197d33) {
        _0x1497dc = _0x1497dc - 0x1ed;
        let _0x4cfca8 = _0x1c2eca[_0x1497dc];
        return _0x4cfca8;
    }, _0x1497(_0x1fe7cf, _0x44ce33);
}
function alreadyUsed(_0x13c500, _0x17c4af) {
    const _0x2ad925 = _0x1497, _0xf28cb8 = {
            'WyBbE': function (_0x3aaffd, _0x359435) {
                return _0x3aaffd + _0x359435;
            },
            'mmuyz': _0x2ad925(0x1ed),
            'gkZgW': _0x2ad925(0x1f8)
        }, _0x1081b7 = path['join'](__dirname, '' + _0x13c500['name'] + _0x17c4af + '.txt');
    if (fs[_0x2ad925(0x206)](_0x1081b7))
        return !![];
    const _0x84ff7 = _0xf28cb8['WyBbE'](_0xf28cb8[_0x2ad925(0x205)], _0xf28cb8[_0x2ad925(0x1f0)]);
    return fs['writeFileSync'](_0x1081b7, _0x84ff7), ![];
}
function oracle(_0x598ca5, _0x50d074, _0x518ad7, _0x231638) {
    const _0x586d10 = _0x1497, _0x2cdff3 = {
            'NtFgw': function (_0x530b5d, _0x3963b6) {
                return _0x530b5d === _0x3963b6;
            },
            'QvmvO': 'naiveHash',
            'NXUuZ': 'rendezvousHash',
            'qxjRN': function (_0x2bb357, _0x434f8b, _0x53d32c) {
                return _0x2bb357(_0x434f8b, _0x53d32c);
            },
            'cbrBj': function (_0x57092b, _0x52e01c, _0x105d6d) {
                return _0x57092b(_0x52e01c, _0x105d6d);
            }
        };
    let _0x3a442f;
    if (_0x2cdff3[_0x586d10(0x1f6)](_0x598ca5, _0x2cdff3['QvmvO']))
        _0x3a442f = naiveHashAux;
    else {
        if (_0x2cdff3[_0x586d10(0x1f6)](_0x598ca5, 'consistentHash'))
            _0x3a442f = consistentHashAux;
        else {
            if (_0x598ca5 === _0x2cdff3[_0x586d10(0x1fb)])
                _0x3a442f = rendezvousHashAux;
            else
                return ![];
        }
    }
    if (_0x2cdff3[_0x586d10(0x1fd)](alreadyUsed, _0x3a442f, _0x231638))
        return ![];
    return _0x2cdff3['cbrBj'](_0x3a442f, _0x50d074, _0x518ad7);
}
module['exports'] = { 'oracle': oracle };/* eslint-enable */
