/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x523213 = _0x27fe;
(function (_0x1b8f2b, _0x42510a) {
    const _0x3c5f1a = _0x27fe, _0x45febd = _0x1b8f2b();
    while (!![]) {
        try {
            const _0x412562 = parseInt(_0x3c5f1a(0x1cd)) / 0x1 + parseInt(_0x3c5f1a(0x1d9)) / 0x2 * (-parseInt(_0x3c5f1a(0x1d2)) / 0x3) + parseInt(_0x3c5f1a(0x1d0)) / 0x4 + parseInt(_0x3c5f1a(0x1db)) / 0x5 * (-parseInt(_0x3c5f1a(0x1d5)) / 0x6) + -parseInt(_0x3c5f1a(0x1d6)) / 0x7 + parseInt(_0x3c5f1a(0x1d3)) / 0x8 * (parseInt(_0x3c5f1a(0x1c8)) / 0x9) + parseInt(_0x3c5f1a(0x1c9)) / 0xa * (parseInt(_0x3c5f1a(0x1cf)) / 0xb);
            if (_0x412562 === _0x42510a)
                break;
            else
                _0x45febd['push'](_0x45febd['shift']());
        } catch (_0x57a1df) {
            _0x45febd['push'](_0x45febd['shift']());
        }
    }
}(_0xd80d, 0xd2aa3));
function _0xd80d() {
    const _0x38af71 = [
        'global',
        '22vxZuxR',
        '1758560aEiZbm',
        'groups',
        '255cAKUqb',
        '264fSdVwG',
        'service',
        '47490uOqIZu',
        '7071778GeYDJX',
        'keys',
        'local',
        '33338avMgAf',
        'method',
        '250XATYiI',
        'length',
        'jNkZx',
        'port',
        'gid',
        'tTsxU',
        '18189ERaYjq',
        '15265090QcOqWW',
        'get',
        'distribution',
        'exports',
        '126401KkRISe'
    ];
    _0xd80d = function () {
        return _0x38af71;
    };
    return _0xd80d();
}
function _0x27fe(_0x34d54d, _0x54a97a) {
    const _0xd80d5c = _0xd80d();
    return _0x27fe = function (_0x27fe17, _0x2eae75) {
        _0x27fe17 = _0x27fe17 - 0x1c5;
        let _0xe4116a = _0xd80d5c[_0x27fe17];
        return _0xe4116a;
    }, _0x27fe(_0x34d54d, _0x54a97a);
}
const comm = function (_0x201ae4) {
    const _0xbe45ef = _0x27fe, _0x271464 = {
            'cFKVq': function (_0x25f717, _0x3f9dc9) {
                return _0x25f717 === _0x3f9dc9;
            },
            'XagRq': function (_0x1c5f71, _0x2f5938, _0x5b11fb) {
                return _0x1c5f71(_0x2f5938, _0x5b11fb);
            },
            'tTsxU': _0xbe45ef(0x1ce)
        };
    let _0x4ba938 = {};
    return _0x4ba938[_0xbe45ef(0x1c6)] = _0x201ae4[_0xbe45ef(0x1c6)] || _0x271464[_0xbe45ef(0x1c7)], {
        'send': (_0x17c443, _0x57d536, _0x33fffd) => {
            const _0x229d36 = _0xbe45ef;
            global[_0x229d36(0x1cb)]['local'][_0x229d36(0x1d1)][_0x229d36(0x1ca)](_0x4ba938['gid'], (_0x2883d0, _0x47cd75) => {
                const _0x2b72b4 = _0x229d36, _0x18b1e2 = {
                        'jNkZx': function (_0x3c4eef, _0x4dfea1) {
                            return _0x271464['cFKVq'](_0x3c4eef, _0x4dfea1);
                        },
                        'pQCtw': function (_0x27d8e8, _0x24916d, _0x3ad3e8) {
                            return _0x271464['XagRq'](_0x27d8e8, _0x24916d, _0x3ad3e8);
                        }
                    };
                let _0x1dcd06 = Object['keys'](_0x47cd75)[_0x2b72b4(0x1dc)], _0x5c3047 = 0x0, _0x3a73b4 = {}, _0x1fd09f = {};
                for (let _0x126093 of Object[_0x2b72b4(0x1d7)](_0x47cd75)) {
                    let _0x7e22ba = _0x47cd75[_0x126093], _0x1c61a6 = {
                            'node': {
                                'ip': _0x7e22ba['ip'],
                                'port': _0x7e22ba[_0x2b72b4(0x1c5)]
                            },
                            'service': _0x57d536[_0x2b72b4(0x1d4)],
                            'method': _0x57d536[_0x2b72b4(0x1da)]
                        };
                    distribution[_0x2b72b4(0x1d8)]['comm']['send'](_0x17c443, _0x1c61a6, (_0x2aed01, _0x391573) => {
                        const _0x7540f2 = _0x2b72b4;
                        _0x2aed01 ? _0x1fd09f[_0x126093] = _0x2aed01 : _0x3a73b4[_0x126093] = _0x391573, _0x5c3047 += 0x1, _0x18b1e2[_0x7540f2(0x1dd)](_0x5c3047, _0x1dcd06) && _0x18b1e2['pQCtw'](_0x33fffd, _0x1fd09f, _0x3a73b4);
                    });
                }
            });
        }
    };
};
module[_0x523213(0x1cc)] = comm;/* eslint-enable */
