/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x3b58c4 = _0x5b52;
(function (_0x2dad21, _0x478682) {
    const _0x2b410f = _0x5b52, _0x26f521 = _0x2dad21();
    while (!![]) {
        try {
            const _0x1c29e9 = parseInt(_0x2b410f(0x16c)) / 0x1 * (-parseInt(_0x2b410f(0x172)) / 0x2) + -parseInt(_0x2b410f(0x174)) / 0x3 * (-parseInt(_0x2b410f(0x15e)) / 0x4) + -parseInt(_0x2b410f(0x180)) / 0x5 * (-parseInt(_0x2b410f(0x173)) / 0x6) + parseInt(_0x2b410f(0x17f)) / 0x7 * (-parseInt(_0x2b410f(0x17a)) / 0x8) + -parseInt(_0x2b410f(0x16a)) / 0x9 * (-parseInt(_0x2b410f(0x16d)) / 0xa) + -parseInt(_0x2b410f(0x15c)) / 0xb * (-parseInt(_0x2b410f(0x168)) / 0xc) + parseInt(_0x2b410f(0x183)) / 0xd * (-parseInt(_0x2b410f(0x17e)) / 0xe);
            if (_0x1c29e9 === _0x478682)
                break;
            else
                _0x26f521['push'](_0x26f521['shift']());
        } catch (_0x518324) {
            _0x26f521['push'](_0x26f521['shift']());
        }
    }
}(_0x43a6, 0xa2316));
function _0x43a6() {
    const _0x18abf9 = [
        'random',
        'GJQnj',
        'local',
        '110696gZzdNC',
        'length',
        'global',
        'subset',
        '14SjfdDa',
        '336tDlgel',
        '439675BwWiYs',
        'SAuib',
        'GZUXw',
        '24386713nadPLe',
        'recv',
        'getTime',
        'add',
        'distribution',
        'HiRSm',
        '374DUZFxD',
        'log',
        '5134196wXUNol',
        'groups',
        'get',
        'send',
        'exports',
        'mid',
        'mss',
        'size',
        'yISni',
        'gossip',
        '373032KoBybv',
        'gid',
        '153pcOYdy',
        'floor',
        '82013ZqaojX',
        '721550XxxFBt',
        'getID',
        'port',
        'XlEAS',
        'keys',
        '26WadzLm',
        '48TdltHT',
        '3HzZfLW',
        'ceil',
        'rrMXS'
    ];
    _0x43a6 = function () {
        return _0x18abf9;
    };
    return _0x43a6();
}
function _0x5b52(_0x1b1c14, _0x55ba91) {
    const _0x43a6b1 = _0x43a6();
    return _0x5b52 = function (_0x5b5225, _0x4498a8) {
        _0x5b5225 = _0x5b5225 - 0x158;
        let _0x342cce = _0x43a6b1[_0x5b5225];
        return _0x342cce;
    }, _0x5b52(_0x1b1c14, _0x55ba91);
}
const id = require('../util/id');
function getMID(_0x55486e) {
    const _0x47b70d = _0x5b52;
    let _0x2d8681 = {};
    return _0x2d8681['date'] = new Date()[_0x47b70d(0x158)](), _0x2d8681[_0x47b70d(0x164)] = _0x55486e, id[_0x47b70d(0x16e)](_0x2d8681);
}
let gossip = function (_0x48ed24) {
    const _0x297f46 = _0x5b52, _0x105ec1 = {
            'HiRSm': function (_0x12bff0, _0xaf386) {
                return _0x12bff0 < _0xaf386;
            },
            'yISni': function (_0x11a4e3, _0x514c55) {
                return _0x11a4e3(_0x514c55);
            },
            'rrMXS': function (_0x166749, _0x490e11, _0xaa4eb4) {
                return _0x166749(_0x490e11, _0xaa4eb4);
            },
            'XlEAS': function (_0x4461d1, _0x10effb, _0x1fd129) {
                return _0x4461d1(_0x10effb, _0x1fd129);
            },
            'vKUSa': _0x297f46(0x17c)
        };
    let _0x41958f = {};
    return _0x41958f['gid'] = _0x48ed24[_0x297f46(0x169)] || _0x105ec1['vKUSa'], _0x41958f[_0x297f46(0x17d)] = _0x48ed24[_0x297f46(0x17d)] || function (_0x557996) {
        const _0x2bb7b9 = _0x297f46;
        return Math[_0x2bb7b9(0x175)](Math[_0x2bb7b9(0x15d)](_0x557996[_0x2bb7b9(0x17b)]));
    }, {
        'send': (_0x33cd96, _0x2710d9, _0x252b62) => {
            const _0xaa024b = _0x297f46, _0x5a307f = {
                    'GJQnj': function (_0x409b40, _0x43a592) {
                        const _0x392885 = _0x5b52;
                        return _0x105ec1[_0x392885(0x15b)](_0x409b40, _0x43a592);
                    },
                    'gMlnw': function (_0x27a5b3, _0x460f9c, _0x2125eb) {
                        return _0x27a5b3(_0x460f9c, _0x2125eb);
                    },
                    'SAuib': function (_0xe8947d, _0xfdb2e8) {
                        const _0x15a022 = _0x5b52;
                        return _0x105ec1[_0x15a022(0x166)](_0xe8947d, _0xfdb2e8);
                    }
                };
            global[_0xaa024b(0x15a)][_0xaa024b(0x179)][_0xaa024b(0x15f)][_0xaa024b(0x160)](_0x41958f['gid'], (_0xb4bb41, _0xab06ec) => {
                const _0x108762 = _0xaa024b, _0x49b4b6 = {
                        'zsoQy': function (_0x225780, _0x15da42) {
                            return _0x225780 === _0x15da42;
                        },
                        'GZUXw': function (_0x3c9cef, _0x33f16f, _0x4afed9) {
                            return _0x5a307f['gMlnw'](_0x3c9cef, _0x33f16f, _0x4afed9);
                        }
                    };
                let _0x55adbf = _0x41958f[_0x108762(0x17d)](Object[_0x108762(0x171)](_0xab06ec)), _0x1ac223 = function (_0x5994fb) {
                        const _0x37e0f5 = _0x108762;
                        let _0xb67816 = new Set();
                        while (_0x5a307f[_0x37e0f5(0x178)](_0xb67816[_0x37e0f5(0x165)], _0x55adbf)) {
                            let _0xa15914 = Math[_0x37e0f5(0x16b)](Math[_0x37e0f5(0x177)]() * _0x5994fb[_0x37e0f5(0x17b)]);
                            _0xb67816[_0x37e0f5(0x159)](_0x5994fb[_0xa15914]);
                        }
                        return _0xb67816;
                    }, _0x1d3961 = _0x5a307f[_0x108762(0x181)](_0x1ac223, Object[_0x108762(0x171)](_0xab06ec)), _0x2b1845 = {}, _0x87392c = {}, _0x4036db = 0x0;
                if (_0x33cd96[_0x108762(0x163)] && _0x33cd96[_0x108762(0x169)]) {
                } else
                    _0x33cd96 = {
                        'message': _0x33cd96,
                        'remote': _0x2710d9,
                        'mid': _0x5a307f[_0x108762(0x181)](getMID, _0x33cd96),
                        'gid': _0x41958f['gid']
                    };
                for (let _0xbeb59c of _0x1d3961) {
                    let _0x358f2a = _0xab06ec[_0xbeb59c], _0x11ea2d = {
                            'node': {
                                'ip': _0x358f2a['ip'],
                                'port': _0x358f2a[_0x108762(0x16f)]
                            },
                            'service': _0x108762(0x167),
                            'method': _0x108762(0x184)
                        };
                    global['distribution'][_0x108762(0x179)]['comm'][_0x108762(0x161)]([_0x33cd96], _0x11ea2d, (_0x4e7904, _0xe7cd07) => {
                        const _0x4961d7 = _0x108762;
                        _0x4e7904 ? _0x87392c[_0xbeb59c] = _0x4e7904 : _0x2b1845[_0xbeb59c] = _0xe7cd07, _0x4036db += 0x1, _0x49b4b6['zsoQy'](_0x4036db, _0x55adbf) && (_0x252b62 && _0x49b4b6[_0x4961d7(0x182)](_0x252b62, _0x87392c, _0x2b1845));
                    });
                }
            });
        },
        'at': (_0x53975f, _0x3902aa, _0x4e9eb2) => {
            const _0x43e961 = _0x297f46;
            let _0x4b6ae1 = _0x105ec1[_0x43e961(0x176)](setInterval, _0x3902aa, _0x53975f);
            _0x4e9eb2 && _0x105ec1[_0x43e961(0x170)](_0x4e9eb2, null, _0x4b6ae1);
        },
        'del': (_0xc16188, _0x5a88b8) => {
            const _0x45d534 = _0x297f46;
            clearInterval(_0xc16188), _0x5a88b8 && _0x105ec1[_0x45d534(0x176)](_0x5a88b8, null, _0xc16188);
        }
    };
};
module[_0x3b58c4(0x162)] = gossip;/* eslint-enable */
