/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
function _0x5afd(_0x4354b3, _0x4f16df) {
    const _0x30701b = _0x3070();
    return _0x5afd = function (_0x5afd1a, _0xd67343) {
        _0x5afd1a = _0x5afd1a - 0xff;
        let _0x1252ee = _0x30701b[_0x5afd1a];
        return _0x1252ee;
    }, _0x5afd(_0x4354b3, _0x4f16df);
}
const _0x330e34 = _0x5afd;
(function (_0x2d6770, _0x1ec43a) {
    const _0x7218bf = _0x5afd, _0xc0b685 = _0x2d6770();
    while (!![]) {
        try {
            const _0x480df4 = -parseInt(_0x7218bf(0x117)) / 0x1 + parseInt(_0x7218bf(0x10e)) / 0x2 * (parseInt(_0x7218bf(0x109)) / 0x3) + parseInt(_0x7218bf(0x115)) / 0x4 + -parseInt(_0x7218bf(0x114)) / 0x5 + parseInt(_0x7218bf(0x113)) / 0x6 * (parseInt(_0x7218bf(0x107)) / 0x7) + parseInt(_0x7218bf(0x100)) / 0x8 * (-parseInt(_0x7218bf(0x101)) / 0x9) + -parseInt(_0x7218bf(0xff)) / 0xa * (parseInt(_0x7218bf(0x106)) / 0xb);
            if (_0x480df4 === _0x1ec43a)
                break;
            else
                _0xc0b685['push'](_0xc0b685['shift']());
        } catch (_0x48974b) {
            _0xc0b685['push'](_0xc0b685['shift']());
        }
    }
}(_0x3070, 0x57b30));
const groups = function (_0x301b36) {
    const _0x531dba = _0x5afd, _0x33b07a = {
            'oEFak': _0x531dba(0x118),
            'NdPPx': _0x531dba(0x108),
            'OZPdv': _0x531dba(0x112),
            'hSQAW': _0x531dba(0x102),
            'gFafs': function (_0x1af5eb, _0x396af9) {
                return _0x1af5eb(_0x396af9);
            },
            'xUIGx': _0x531dba(0x104),
            'uUbjg': 'global'
        };
    let _0x12d6d1 = {};
    return _0x12d6d1[_0x531dba(0x111)] = _0x301b36['gid'] || _0x33b07a['uUbjg'], {
        'put': (_0xb5271f, _0x4e0243, _0x2747c6) => {
            const _0x8f8546 = _0x531dba;
            global[_0x8f8546(0x10f)][_0x8f8546(0x10a)][_0x8f8546(0x118)][_0x8f8546(0x108)](_0xb5271f, _0x4e0243, (_0xc59ef0, _0x2444f5) => {
                const _0xaa8452 = _0x8f8546;
                _0xc59ef0 && _0x2747c6(_0xc59ef0), global[_0xaa8452(0x10f)][_0x12d6d1['gid']]['comm'][_0xaa8452(0x110)]([
                    _0xb5271f,
                    _0x4e0243
                ], {
                    'service': _0x33b07a['oEFak'],
                    'method': _0x33b07a['NdPPx']
                }, _0x2747c6);
            });
        },
        'del': (_0x59277b, _0x73a0b0) => {
            const _0x5cc5e4 = _0x531dba;
            global[_0x5cc5e4(0x10f)][_0x12d6d1[_0x5cc5e4(0x111)]][_0x5cc5e4(0x10b)][_0x5cc5e4(0x110)]([_0x59277b], {
                'service': _0x5cc5e4(0x118),
                'method': _0x33b07a[_0x5cc5e4(0x116)]
            }, _0x73a0b0);
        },
        'get': (_0x1d0304, _0x4cbb6) => {
            const _0x2258f1 = _0x531dba;
            global[_0x2258f1(0x10f)][_0x12d6d1[_0x2258f1(0x111)]]['comm']['send']([_0x1d0304], {
                'service': _0x33b07a['oEFak'],
                'method': _0x33b07a['hSQAW']
            }, _0x4cbb6);
        },
        'add': (_0x3e216f, _0x1db29c, _0x4f9367) => {
            const _0x23d196 = _0x531dba;
            global[_0x23d196(0x10f)][_0x23d196(0x10a)][_0x23d196(0x118)][_0x23d196(0x119)](_0x3e216f, _0x1db29c, (_0x492335, _0x41e434) => {
                const _0x3bc5bc = _0x23d196;
                _0x492335 && _0x4f9367(_0x492335), global[_0x3bc5bc(0x10f)][_0x12d6d1[_0x3bc5bc(0x111)]][_0x3bc5bc(0x10b)]['send']([
                    _0x3e216f,
                    _0x1db29c
                ], {
                    'service': _0x33b07a[_0x3bc5bc(0x105)],
                    'method': _0x3bc5bc(0x119)
                }, _0x4f9367);
            });
        },
        'rem': (_0x2cb3c3, _0x4e5b2f, _0x4a7742) => {
            const _0x1673ed = _0x531dba;
            global[_0x1673ed(0x10f)][_0x1673ed(0x10a)][_0x1673ed(0x118)][_0x1673ed(0x104)](_0x2cb3c3, _0x4e5b2f, (_0x225d81, _0x529820) => {
                const _0x3befe6 = _0x1673ed;
                _0x225d81 && _0x33b07a[_0x3befe6(0x10c)](_0x4a7742, _0x225d81), global[_0x3befe6(0x10f)][_0x12d6d1[_0x3befe6(0x111)]][_0x3befe6(0x10b)]['send']([
                    _0x2cb3c3,
                    _0x4e5b2f
                ], {
                    'service': _0x3befe6(0x118),
                    'method': _0x33b07a[_0x3befe6(0x103)]
                }, _0x4a7742);
            });
        }
    };
};
module[_0x330e34(0x10d)] = groups;
function _0x3070() {
    const _0xe5c23d = [
        'add',
        '20FyFuBC',
        '120YopqAT',
        '148644uBxeed',
        'get',
        'xUIGx',
        'rem',
        'oEFak',
        '2762045uvJVHo',
        '2094561FYIppW',
        'put',
        '4215oShbhn',
        'local',
        'comm',
        'gFafs',
        'exports',
        '718bfUjMR',
        'distribution',
        'send',
        'gid',
        'del',
        '6TZcwWA',
        '819905eYrbvh',
        '2308872SDCByB',
        'OZPdv',
        '107709LlYTUI',
        'groups'
    ];
    _0x3070 = function () {
        return _0xe5c23d;
    };
    return _0x3070();
}/* eslint-enable */
