/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
function _0x3ec4(_0x33fbbc, _0x40e1cc) {
    const _0xf596a = _0xf596();
    return _0x3ec4 = function (_0x3ec4e4, _0x7fe4f7) {
        _0x3ec4e4 = _0x3ec4e4 - 0x142;
        let _0x8b39f3 = _0xf596a[_0x3ec4e4];
        return _0x8b39f3;
    }, _0x3ec4(_0x33fbbc, _0x40e1cc);
}
function _0xf596() {
    const _0x5ad4a8 = [
        '68XPLBLI',
        '1719087FhwMvf',
        'gid',
        'comm',
        '9yUnPRw',
        'nNBIU',
        '1640828uhlcWi',
        '66065UgJfgZ',
        'exports',
        'send',
        'distribution',
        'put',
        '6416evqskk',
        '6jMWDlo',
        '11323390LxFIec',
        'ZcYWA',
        '2495040jjbAnq',
        'dTntP',
        '591536TMzCye',
        'routes'
    ];
    _0xf596 = function () {
        return _0x5ad4a8;
    };
    return _0xf596();
}
const _0x3e27cf = _0x3ec4;
(function (_0x353224, _0x4304d0) {
    const _0x32aa78 = _0x3ec4, _0x87e9ac = _0x353224();
    while (!![]) {
        try {
            const _0x449f10 = parseInt(_0x32aa78(0x146)) / 0x1 * (parseInt(_0x32aa78(0x14e)) / 0x2) + -parseInt(_0x32aa78(0x14f)) / 0x3 + -parseInt(_0x32aa78(0x14a)) / 0x4 + parseInt(_0x32aa78(0x155)) / 0x5 * (parseInt(_0x32aa78(0x147)) / 0x6) + parseInt(_0x32aa78(0x154)) / 0x7 + -parseInt(_0x32aa78(0x14c)) / 0x8 + parseInt(_0x32aa78(0x152)) / 0x9 * (parseInt(_0x32aa78(0x148)) / 0xa);
            if (_0x449f10 === _0x4304d0)
                break;
            else
                _0x87e9ac['push'](_0x87e9ac['shift']());
        } catch (_0x1583db) {
            _0x87e9ac['push'](_0x87e9ac['shift']());
        }
    }
}(_0xf596, 0x4fec9));
const routes = function (_0x3f6816) {
    const _0xeb3f72 = _0x3ec4, _0x22d749 = {
            'ZcYWA': _0xeb3f72(0x14d),
            'dTntP': _0xeb3f72(0x145),
            'nNBIU': 'global'
        };
    let _0x24f539 = {};
    return _0x24f539[_0xeb3f72(0x150)] = _0x3f6816[_0xeb3f72(0x150)] || _0x22d749[_0xeb3f72(0x153)], {
        'put': (_0x411954, _0x135cc8, _0x54443a) => {
            const _0x5b8ba2 = _0xeb3f72;
            global[_0x5b8ba2(0x144)][_0x24f539[_0x5b8ba2(0x150)]][_0x5b8ba2(0x151)][_0x5b8ba2(0x143)]([
                _0x411954,
                _0x135cc8
            ], {
                'service': _0x22d749[_0x5b8ba2(0x149)],
                'method': _0x22d749[_0x5b8ba2(0x14b)]
            }, _0x54443a);
        }
    };
};
module[_0x3e27cf(0x142)] = routes;/* eslint-enable */
