/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x8d59bc = _0x1509;
(function (_0x18ab8f, _0xb26006) {
    const _0x4b1488 = _0x1509, _0x50d415 = _0x18ab8f();
    while (!![]) {
        try {
            const _0x3f34f4 = parseInt(_0x4b1488(0x93)) / 0x1 + parseInt(_0x4b1488(0x8d)) / 0x2 + -parseInt(_0x4b1488(0x95)) / 0x3 * (-parseInt(_0x4b1488(0x7a)) / 0x4) + parseInt(_0x4b1488(0x9f)) / 0x5 * (parseInt(_0x4b1488(0x9b)) / 0x6) + parseInt(_0x4b1488(0x8f)) / 0x7 * (-parseInt(_0x4b1488(0x82)) / 0x8) + parseInt(_0x4b1488(0x7b)) / 0x9 * (-parseInt(_0x4b1488(0x96)) / 0xa) + parseInt(_0x4b1488(0x7e)) / 0xb * (-parseInt(_0x4b1488(0x92)) / 0xc);
            if (_0x3f34f4 === _0xb26006)
                break;
            else
                _0x50d415['push'](_0x50d415['shift']());
        } catch (_0x289e92) {
            _0x50d415['push'](_0x50d415['shift']());
        }
    }
}(_0x4996, 0xa280b));
function _0x1509(_0x5b6a50, _0x518623) {
    const _0x499696 = _0x4996();
    return _0x1509 = function (_0x150933, _0x4c3098) {
        _0x150933 = _0x150933 - 0x77;
        let _0x1a39d2 = _0x499696[_0x150933];
        return _0x1a39d2;
    }, _0x1509(_0x5b6a50, _0x518623);
}
const status = function (_0x4eb37c) {
    const _0x3a59bb = _0x1509, _0x189a01 = {
            'XNKzI': function (_0x43c8ec, _0x2c69b4) {
                return _0x43c8ec + _0x2c69b4;
            },
            'AtBAB': _0x3a59bb(0x79),
            'aBXbd': function (_0x49cf45, _0x5bbdab, _0x17dbfe) {
                return _0x49cf45(_0x5bbdab, _0x17dbfe);
            },
            'zPMPy': function (_0x33dcdd, _0xb462a5, _0x3b2c7d) {
                return _0x33dcdd(_0xb462a5, _0x3b2c7d);
            },
            'KmRQV': _0x3a59bb(0x94),
            'vLRvd': function (_0x55c20d, _0x2dd9e1) {
                return _0x55c20d(_0x2dd9e1);
            },
            'vaWpU': _0x3a59bb(0x91),
            'UxGmS': _0x3a59bb(0x8e),
            'nTpDN': _0x3a59bb(0x87)
        };
    let _0x116907 = {};
    return _0x116907[_0x3a59bb(0x9d)] = _0x4eb37c[_0x3a59bb(0x9d)] || _0x189a01[_0x3a59bb(0x98)], {
        'get': (_0x3cbe36, _0x353115) => {
            const _0x57841a = _0x3a59bb, _0x28f07e = {
                    'DwZfI': function (_0x5ee621, _0x28f43a) {
                        const _0x2d40b4 = _0x1509;
                        return _0x189a01[_0x2d40b4(0x9e)](_0x5ee621, _0x28f43a);
                    },
                    'HjVEf': _0x189a01['AtBAB'],
                    'zCRsw': function (_0x1917c6, _0x1c4350, _0x5db828) {
                        const _0x6cb485 = _0x1509;
                        return _0x189a01[_0x6cb485(0x7f)](_0x1917c6, _0x1c4350, _0x5db828);
                    },
                    'DglEr': _0x57841a(0x9c),
                    'DKHGr': function (_0x1d6593, _0x2c8323, _0x1be135) {
                        const _0x27c5c0 = _0x57841a;
                        return _0x189a01[_0x27c5c0(0x8b)](_0x1d6593, _0x2c8323, _0x1be135);
                    },
                    'oDvZD': function (_0xf90a6c, _0x4104f9, _0x126285) {
                        return _0xf90a6c(_0x4104f9, _0x126285);
                    }
                };
            let _0x3c0ca7 = [_0x3cbe36], _0x1870a9 = {
                    'service': _0x57841a(0x8e),
                    'method': _0x189a01[_0x57841a(0x84)]
                };
            global[_0x57841a(0x7d)][_0x116907[_0x57841a(0x9d)]][_0x57841a(0x97)][_0x57841a(0x78)](_0x3c0ca7, _0x1870a9, (_0xae99ad, _0x44909e) => {
                const _0x50ab7a = _0x57841a;
                switch (_0x3cbe36) {
                case _0x28f07e[_0x50ab7a(0x88)]:
                    let _0x34eea7 = Object[_0x50ab7a(0x80)](_0x44909e)[_0x50ab7a(0x7c)]((_0x58ec28, _0x2ed329) => {
                        const _0x40d37b = _0x50ab7a;
                        return _0x28f07e[_0x40d37b(0x81)](_0x58ec28, _0x2ed329);
                    }, 0x0);
                    _0x28f07e[_0x50ab7a(0x9a)](_0x353115, _0xae99ad, _0x34eea7);
                    break;
                case _0x28f07e['DglEr']:
                    let _0x6b8ff2 = Object[_0x50ab7a(0x80)](_0x44909e)[_0x50ab7a(0x7c)]((_0x2fc1fe, _0x11f54e) => {
                        const _0x50e14d = _0x50ab7a;
                        return _0x2fc1fe[_0x50e14d(0x85)](_0x11f54e);
                    }, []);
                    _0x28f07e[_0x50ab7a(0x90)](_0x353115, _0xae99ad, _0x6b8ff2);
                    break;
                default:
                    _0x28f07e[_0x50ab7a(0xa0)](_0x353115, _0xae99ad, _0x44909e);
                    break;
                }
            });
        },
        'spawn': (_0x1517e4, _0x12b461) => {
            const _0x1db8f0 = _0x3a59bb;
            _0x12b461 = _0x12b461 || function () {
            }, global['distribution'][_0x1db8f0(0x86)][_0x1db8f0(0x8e)][_0x1db8f0(0x8c)](_0x1517e4, (_0x2749b7, _0x3ed3f7) => {
                const _0x2e7d51 = _0x1db8f0;
                _0x2749b7 ? _0x189a01['vLRvd'](_0x12b461, _0x2749b7) : global[_0x2e7d51(0x7d)][_0x2e7d51(0x86)]['groups'][_0x2e7d51(0x91)](_0x116907['gid'], _0x1517e4, () => {
                    _0x12b461(null, _0x3ed3f7);
                }), distribution[_0x116907[_0x2e7d51(0x9d)]]['comm']['send']([
                    _0x116907[_0x2e7d51(0x9d)],
                    _0x1517e4
                ], {
                    'service': _0x2e7d51(0x99),
                    'method': _0x189a01[_0x2e7d51(0x83)]
                }, () => {
                });
            });
        },
        'stop': _0x509085 => {
            const _0x25c207 = _0x3a59bb;
            distribution[_0x116907['gid']][_0x25c207(0x97)][_0x25c207(0x78)]([], {
                'service': _0x189a01[_0x25c207(0x77)],
                'method': _0x25c207(0x89)
            }, _0x509085);
        }
    };
};
module[_0x8d59bc(0x8a)] = status;
function _0x4996() {
    const _0x5d3754 = [
        'DKHGr',
        'add',
        '5911548uPHUBV',
        '718817sMrNRF',
        'get',
        '15dpIzAU',
        '44260TGHuSq',
        'comm',
        'nTpDN',
        'groups',
        'zCRsw',
        '24vppjwW',
        'nid',
        'gid',
        'XNKzI',
        '1319165zksyTy',
        'oDvZD',
        'UxGmS',
        'send',
        'heapTotal',
        '738860RhaGbT',
        '1773eHSIeD',
        'reduce',
        'distribution',
        '44kHhRWf',
        'aBXbd',
        'values',
        'DwZfI',
        '2480fLCrir',
        'vaWpU',
        'KmRQV',
        'concat',
        'local',
        'global',
        'HjVEf',
        'stop',
        'exports',
        'zPMPy',
        'spawn',
        '1951730tVopaV',
        'status',
        '3738pxApPU'
    ];
    _0x4996 = function () {
        return _0x5d3754;
    };
    return _0x4996();
}/* eslint-enable */
